name: DEVELOP


on:
  push:
    branches: [develop]
  pull_request:
    types: [closed]
    branches: [develop]
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/nazar-blaize/soul-search-3
          envkey_IMAGES_S3_BUCKET: soulsearch
          envkey_IMAGES_S3_REGION: eu-central-1
          envkey_SKIP_DATABASE_CREATION: true
          file_name: dev.env
      - name: build docker image
        run: |
          export name=$(echo ${GITHUB_REPOSITORY#*/}"-develop" | tr '[:upper:]' '[:lower:]')
          export key="web-toshi-site"
          export timestamp=$(date +%s)
          export host=${{secrets.HOST}}
          docker build . -t ${name}-${timestamp}
          docker save -o ${name}-${timestamp}.tar ${name}-${timestamp}
          echo "${{secrets.SSH_PRIV}}" > ${key}
          sudo chmod 600 ${key}
          
          echo "name=${name}" >> develop.txt
          echo "key1=${key}" >> develop.txt
          echo "timestamp=${timestamp}" >> develop.txt
          echo "name=${name}" >> develop.txt
          echo "key2=${key}" >> develop.txt
          echo "HOST=${host}" >> develop.txt
          scp -i ${key} -o "StrictHostKeyChecking no" develop.txt ${host}:/home/ubuntu/develop-back.txt
          scp -i ${key} -o "StrictHostKeyChecking no" dev.env ${host}:/home/ubuntu/dev.env
          
          scp -i ${key} -o "StrictHostKeyChecking no" ${name}-${timestamp}.tar ${host}:${name}-${timestamp}.tar
          ssh -i ${key} -o "StrictHostKeyChecking no" ${host} 'sudo docker load -i '${name}'-'${timestamp}'.tar; sudo docker stop '${name}' || true; sudo docker run -d  --restart always --env-file dev.env -p 4445:3000 --name '${name}'-new '${name}'-'${timestamp}'; sudo docker rm '${name}' || true; sudo docker rmi $(sudo docker images -q) || true; sudo docker rename '${name}'-new '${name}'; rm '${name}'-'${timestamp}'.tar'
